### ISSUE TITLE
ul:nth-child(1) css style

### ISSUE THREAD

**Issue by vorotech** [olton/Metro-UI-CSS#145]
Hi Sergey,

Could you please clarify what is the purpose of the css style in modern.css (line 2471):

``` css
ul:nth-child(1) {
  margin-left: 25px;
}
```

Because of that my list view items looks corrupted. Why the first ul's item should have left margin?
![image](https://f.cloud.github.com/assets/2937451/152342/a09e1960-75c0-11e2-8f2d-5ff3242d041b.png)
