### ISSUE TITLE
[.metro .breadcrumbs ul a:after/defore]'s Color Diffrence

### ISSUE THREAD

**Issue by Gaubee** [olton/Metro-UI-CSS#473]
not #DDD; but #D9D9D9.
```css
.metro .breadcrumbs ul a:after {
content: "";
position: absolute;
top: 50%;
margin-top: -1.5em;
border-top: 1.5em solid rgba(0, 0, 0, 0);
border-bottom: 1.5em solid rgba(0, 0, 0, 0);
border-left: 1em solid #D9D9D9;
right: -1em;
margin-right: 1px;
}
.metro .breadcrumbs ul a:before {
content: "";
position: absolute;
top: 50%;
margin-top: -1.5em;
border-width: 1.5em 0 1.5em 1em;
border-style: solid;
border-color: #D9D9D9 #D9D9D9 #D9D9D9 rgba(0, 0, 0, 0);
left: -1em;
margin-left: 1px;
}
```
