### ISSUE TITLE
[SUGGEST]  I would like to mix icon with image in my Tile

### ISSUE THREAD

**Issue by Gaubee** [olton/Metro-UI-CSS#474]
For exmaple ,On the cover of the album music I want to use a `play-alt` icon:
```css
.metro .tile .tile-content.icon.image img {
width: auto;
height: auto;
top: 28px;
left: 28px;
}
```
you konwn what I say.(^_^)
