### ISSUE TITLE
Compact Horizontal menu with dropdown

### ISSUE THREAD

**Issue by REJack** [olton/Metro-UI-CSS#623]
The first Dropdown item has no margin but any after got 5px from the compact class on horizontal-menu

![metroui_issue](https://cloud.githubusercontent.com/assets/1554582/4134592/fd029e62-336d-11e4-99e3-7c54c26d8b4c.jpg)

i have fixed it for me with
metro-bootstrap.css line 3571
```css
.metro .horizontal-menu.compact li {
  margin-left: 5px;
}
```
to
```css
.metro .horizontal-menu.compact ul > li {
  margin-left: 5px;
}
.metro .horizontal-menu.compact ul ul > li {
  margin-left: 0px;
}
```
