### ISSUE TITLE
Adding select to appbar, broken in Chrome and Edge

### ISSUE THREAD

**Issue by akotulu** [olton/Metro-UI-CSS#848]
Firefox displays select correctly without rounded borders and shadow, but Chrome and Edge both render rounded corners and grey background.

```
<form action="xxx" method="post">
  <ul class="app-bar-menu place-right">
    <li class="no-hover">
      <div class="input-control text">
        <select class="search-menu" name="menu">
          <option value="0">0</option>
          <option value="1">1</option>
        </select>
      </div>
    </li>
    <li class="no-hover">
      <div class="input-control text" data-role="input">
        <input type="text">
        <button class="button">
          <span class="mif-search"></span>
        </button>
      </div>
    </li>
  </ul>
</form>
```

This fixed the problem

``` css
.search-menu {
    border-radius: 0px;
    border-right-style: none !important;
    border: 0px solid #d9d9d9 !important;
    background: white;
       -webkit-appearance: none;
}
```
